language: ruby
sudo: false
dist: bionic
arch: ppc64le
services:
  - postgresql
include:
- os: linux
  addons:
    packages:
    - build-essential
    - make
    - gcc
    - wget
    - gem
    - shared-mime-info.ppc64le
    - zlib.ppc64le
    - zlib-devel.ppc64le

before_install:
  - sudo apt-get update
  - ./ci/setup_${TRAVIS_OS_NAME}_environment.sh

script:
  - ./ci/setup.sh
